name: exploration_missing_values
channels:
  - conda-forge
  - defaults
dependencies:
  - fs
  - jupyter
  - jupyterlab
  - matplotlib
  - numpy
  - pandas
  - pathlib
  - pip
  - pyprojroot
  - python=3.7
  - scipy
  - seaborn
  - statsmodels
  - pyreadr
  - missingno
  - upsetplot
